// ---------------------------------------------------------------
// 소스 DB 의 public 스키마를 SQL 로 내려받기
// 사용:
//   node scripts/dump-schema.mjs                    # .env.local 의 DATABASE_URL 사용 → schema-dump.sql
//   node scripts/dump-schema.mjs --url "<URI>"      # 명시 지정
//   node scripts/dump-schema.mjs --out schema.sql   # 출력 파일 지정
//   node scripts/dump-schema.mjs --data             # 데이터(INSERT)도 같이 덤프
//
// 산출물: 새 Supabase 프로젝트의 SQL Editor 에 붙여넣어 실행 가능한 SQL.
// 포함: 테이블/컬럼/PK/FK/UNIQUE/CHECK/인덱스/시퀀스/RLS enable+policies/트리거 정의.
// 미포함: 함수·뷰·머티리얼라이즈드뷰·EXTENSION·storage 스키마(Supabase 기본 외 사용자 추가분 한정).
// ---------------------------------------------------------------
import { readFileSync, existsSync, writeFileSync } from 'fs';
import path from 'path';
import pg from 'pg';

const envPath = path.resolve('.env.local');
if (existsSync(envPath)) {
  for (const l of readFileSync(envPath, 'utf8').split(/\r?\n/)) {
    const m = l.match(/^([^#=\s][^=]*)=(.*)$/);
    if (m && !process.env[m[1].trim()]) process.env[m[1].trim()] = m[2].trim();
  }
}

const argv = process.argv.slice(2);
const getArg = (flag, def = null) => {
  const i = argv.indexOf(flag);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : def;
};
const URL    = getArg('--url') || process.env.DATABASE_URL;
const OUT    = getArg('--out') || 'schema-dump.sql';
const WITH_DATA = argv.includes('--data');

if (!URL) {
  console.error('✗ DATABASE_URL 이 없습니다. --url <URI> 또는 .env.local 에 DATABASE_URL 설정 필요.');
  process.exit(1);
}

// jsonb/json 컬럼을 자동 파싱 없이 raw 텍스트로 받기 (덤프 정확도)
pg.types.setTypeParser(114,  v => v);  // json
pg.types.setTypeParser(3802, v => v);  // jsonb

const client = new pg.Client({ connectionString: URL, ssl: { rejectUnauthorized: false } });
await client.connect();

const out = [];
const w = (s) => out.push(s);

w(`-- Generated by scripts/dump-schema.mjs at ${new Date().toISOString()}`);
w(`-- Source DB: ${URL.replace(/:[^:@]*@/, ':***@')}`);
w(`-- 사용: 새 Supabase 프로젝트의 SQL Editor 에 통째로 붙여넣어 실행`);
w(`SET statement_timeout = 0;`);
w(`SET client_min_messages = warning;`);
w(`SET search_path = public;`);
w('');

// --- 1. 시퀀스 -----------------------------------------------------------
const seqs = (await client.query(`
  SELECT sequence_name, data_type, start_value, minimum_value, maximum_value, increment
  FROM information_schema.sequences
  WHERE sequence_schema = 'public'
  ORDER BY sequence_name;
`)).rows;
if (seqs.length) {
  w('-- ============ Sequences ============');
  for (const s of seqs) {
    w(`CREATE SEQUENCE IF NOT EXISTS public.${quoteIdent(s.sequence_name)} AS ${s.data_type} START WITH ${s.start_value} INCREMENT BY ${s.increment} MINVALUE ${s.minimum_value} MAXVALUE ${s.maximum_value};`);
  }
  w('');
}

// --- 2. 테이블 + 컬럼 ----------------------------------------------------
const tables = (await client.query(`
  SELECT table_name
  FROM information_schema.tables
  WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  ORDER BY table_name;
`)).rows.map(r => r.table_name);

console.log(`테이블 ${tables.length}개 발견:`, tables.join(', '));

for (const t of tables) {
  const cols = (await client.query(`
    SELECT column_name, data_type, udt_name, character_maximum_length, numeric_precision, numeric_scale,
           is_nullable, column_default, identity_generation
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = $1
    ORDER BY ordinal_position;
  `, [t])).rows;

  w(`-- ============ Table: ${t} ============`);
  w(`CREATE TABLE IF NOT EXISTS public.${quoteIdent(t)} (`);
  const lines = cols.map(c => {
    const type = formatType(c);
    const nul = c.is_nullable === 'NO' ? ' NOT NULL' : '';
    const def = c.column_default ? ` DEFAULT ${c.column_default}` : '';
    const ident = c.identity_generation ? ` GENERATED ${c.identity_generation} AS IDENTITY` : '';
    return `  ${quoteIdent(c.column_name)} ${type}${ident}${nul}${def}`;
  });
  w(lines.join(',\n'));
  w(');');
  w('');
}

// --- 3. PK / UNIQUE / CHECK / FK -----------------------------------------
const constraints = (await client.query(`
  SELECT
    tc.table_name,
    tc.constraint_name,
    tc.constraint_type,
    pg_get_constraintdef(c.oid) AS def
  FROM information_schema.table_constraints tc
  JOIN pg_constraint c ON c.conname = tc.constraint_name
  JOIN pg_namespace n ON n.oid = c.connamespace AND n.nspname = tc.table_schema
  WHERE tc.table_schema = 'public'
    AND tc.constraint_type IN ('PRIMARY KEY','UNIQUE','CHECK','FOREIGN KEY')
  ORDER BY tc.table_name,
    CASE tc.constraint_type WHEN 'PRIMARY KEY' THEN 1 WHEN 'UNIQUE' THEN 2 WHEN 'CHECK' THEN 3 ELSE 4 END;
`)).rows;
if (constraints.length) {
  w('-- ============ Constraints ============');
  for (const c of constraints) {
    w(`ALTER TABLE public.${quoteIdent(c.table_name)} ADD CONSTRAINT ${quoteIdent(c.constraint_name)} ${c.def};`);
  }
  w('');
}

// --- 4. 인덱스 (PK/UNIQUE 제외 — 위에서 이미 처리) -----------------------
const indexes = (await client.query(`
  SELECT i.indexrelid::regclass::text AS index_name, t.relname AS table_name, pg_get_indexdef(i.indexrelid) AS def
  FROM pg_index i
  JOIN pg_class t ON t.oid = i.indrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public'
    AND NOT i.indisprimary
    AND NOT i.indisunique
  ORDER BY t.relname, i.indexrelid::regclass::text;
`)).rows;
if (indexes.length) {
  w('-- ============ Indexes (non-PK, non-unique) ============');
  for (const ix of indexes) w(`${ix.def};`);
  w('');
}

// --- 5. RLS (활성화 여부 + 정책) -----------------------------------------
const rlsTables = (await client.query(`
  SELECT relname FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity = true
  ORDER BY relname;
`)).rows.map(r => r.relname);
if (rlsTables.length) {
  w('-- ============ RLS enable ============');
  for (const t of rlsTables) w(`ALTER TABLE public.${quoteIdent(t)} ENABLE ROW LEVEL SECURITY;`);
  w('');
}

const policies = (await client.query(`
  SELECT schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
  FROM pg_policies
  WHERE schemaname = 'public'
  ORDER BY tablename, policyname;
`)).rows;
if (policies.length) {
  w('-- ============ RLS policies ============');
  for (const p of policies) {
    const roles = p.roles && p.roles.length ? p.roles.join(', ') : 'public';
    let sql = `CREATE POLICY ${quoteIdent(p.policyname)} ON public.${quoteIdent(p.tablename)}`;
    sql += ` AS ${p.permissive}`;
    sql += ` FOR ${p.cmd}`;
    sql += ` TO ${roles}`;
    if (p.qual) sql += ` USING (${p.qual})`;
    if (p.with_check) sql += ` WITH CHECK (${p.with_check})`;
    sql += ';';
    w(sql);
  }
  w('');
}

// --- 6. 트리거 (사용자 정의만) -------------------------------------------
const triggers = (await client.query(`
  SELECT tgname, tgrelid::regclass::text AS table_name, pg_get_triggerdef(oid) AS def
  FROM pg_trigger
  WHERE NOT tgisinternal
    AND tgrelid::regclass::text NOT LIKE 'pg_%'
    AND tgrelid IN (SELECT oid FROM pg_class WHERE relnamespace = 'public'::regnamespace)
  ORDER BY tgrelid::regclass::text, tgname;
`)).rows;
if (triggers.length) {
  w('-- ============ Triggers ============');
  w('-- 주의: 트리거가 참조하는 함수가 새 DB 에 없으면 실패합니다. 필요 시 함수 정의를 별도로 옮기세요.');
  for (const t of triggers) w(`${t.def};`);
  w('');
}

// --- 7. 데이터 (옵션) ----------------------------------------------------
if (WITH_DATA) {
  w('-- ============ Data ============');

  // 각 테이블의 컬럼별 타입 맵 미리 조회 (json/jsonb 식별용)
  const colTypes = {}; // colTypes[table][col] = data_type
  for (const t of tables) {
    const rows = (await client.query(`
      SELECT column_name, data_type, udt_name
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = $1
    `, [t])).rows;
    colTypes[t] = {};
    for (const c of rows) colTypes[t][c.column_name] = c.data_type;
  }

  for (const t of tables) {
    const rows = (await client.query(`SELECT * FROM public.${quoteIdent(t)};`)).rows;
    if (!rows.length) continue;
    const cols = Object.keys(rows[0]);
    const colList = cols.map(quoteIdent).join(', ');
    for (const r of rows) {
      const vals = cols.map(c => sqlLiteral(r[c], colTypes[t][c])).join(', ');
      w(`INSERT INTO public.${quoteIdent(t)} (${colList}) VALUES (${vals});`);
    }
    w('');
  }
}

await client.end();

writeFileSync(OUT, out.join('\n'), 'utf8');
console.log(`✓ ${OUT} 생성 완료 (${out.length} 줄)`);
console.log(`  → 새 Supabase 프로젝트의 SQL Editor 에 붙여넣어 실행하세요.`);
if (!WITH_DATA) console.log(`  → 데이터도 함께 덤프하려면 --data 옵션 추가.`);

// --- 헬퍼 ---------------------------------------------------------------
function quoteIdent(name) {
  return /^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name.replace(/"/g, '""')}"`;
}

function formatType(c) {
  const t = c.data_type;
  if (t === 'character varying') return c.character_maximum_length ? `varchar(${c.character_maximum_length})` : 'varchar';
  if (t === 'character') return c.character_maximum_length ? `char(${c.character_maximum_length})` : 'char';
  if (t === 'numeric' && c.numeric_precision) return `numeric(${c.numeric_precision},${c.numeric_scale ?? 0})`;
  if (t === 'ARRAY') return c.udt_name.replace(/^_/, '') + '[]';
  if (t === 'USER-DEFINED') return c.udt_name;
  return t;
}

function sqlLiteral(v, dataType) {
  if (v === null || v === undefined) return 'NULL';

  // json/jsonb 컬럼: 위 setTypeParser 로 raw text 가 string 으로 옴 → 그대로 jsonb 캐스트
  if (dataType === 'json' || dataType === 'jsonb') {
    if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'::${dataType}`;
    // 혹시 객체로 받은 경우 stringify
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::${dataType}`;
  }

  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (v instanceof Date) return `'${v.toISOString()}'`;
  if (Array.isArray(v) || typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}
